reportReasonWithMessage#1b22f19c report_reason:bytes message:string = ReportReasonWithMessage;
userStatusFull#bd76d921 status:Bool expires:int was_online:int = UserStatus;
thumbnail#88a8b83c file_id:long thumb_file_id:long photo_size:bytes = Thumbnail;
appInfo#69abdb23 hash:long auth_key_id:long encrypted_requests_disabled:Bool call_requests_disabled:Bool api_id:int device_model:string system_version:string app_version:string system_lang_code:string lang_pack:string lang_code:string ip:string = AppInfo;

