//  <auto-generated>
//  This file was auto-generated by the Ferrite TL Generator.
//  Please do not modify as all changes will be lost.
//  <auto-generated/>

#nullable enable

namespace Ferrite.TL.slim;

public static class Constructors
{
    
    public const int resPQ = unchecked((int)0x05162463);
    public const int p_q_inner_data = unchecked((int)0x83c95aec);
    public const int p_q_inner_data_temp = unchecked((int)0x3c6a84d4);
    public const int p_q_inner_data_dc = unchecked((int)0xa9f55f95);
    public const int p_q_inner_data_temp_dc = unchecked((int)0x56fddf88);
    public const int server_DH_params_ok = unchecked((int)0xd0e8075c);
    public const int server_DH_inner_data = unchecked((int)0xb5890dba);
    public const int client_DH_inner_data = unchecked((int)0x6643b654);
    public const int dh_gen_ok = unchecked((int)0x3bcbf734);
    public const int dh_gen_retry = unchecked((int)0x46dc1fb9);
    public const int dh_gen_fail = unchecked((int)0xa69dae02);
    public const int bind_auth_key_inner = unchecked((int)0x75a3f765);
    public const int rpc_result = unchecked((int)0xf35c6d01);
    public const int rpc_error = unchecked((int)0x2144ca19);
    public const int rpc_answer_unknown = unchecked((int)0x5e2ad36e);
    public const int rpc_answer_dropped_running = unchecked((int)0xcd78e586);
    public const int rpc_answer_dropped = unchecked((int)0xa43ad8b7);
    public const int future_salt = unchecked((int)0x0949d9dc);
    public const int future_salts = unchecked((int)0xae500895);
    public const int pong = unchecked((int)0x347773c5);
    public const int destroy_session_ok = unchecked((int)0xe22045fc);
    public const int destroy_session_none = unchecked((int)0x62d350c9);
    public const int new_session_created = unchecked((int)0x9ec20908);
    public const int msg_container = unchecked((int)0x73f1f8dc);
    public const int msg_copy = unchecked((int)0xe06046b2);
    public const int gzip_packed = unchecked((int)0x3072cfa1);
    public const int msgs_ack = unchecked((int)0x62d6b459);
    public const int bad_msg_notification = unchecked((int)0xa7eff811);
    public const int bad_server_salt = unchecked((int)0xedab447b);
    public const int msg_resend_req = unchecked((int)0x7d861a08);
    public const int msgs_state_req = unchecked((int)0xda69fb52);
    public const int msgs_state_info = unchecked((int)0x04deb57d);
    public const int msgs_all_info = unchecked((int)0x8cc0d131);
    public const int msg_detailed_info = unchecked((int)0x276d3ec6);
    public const int msg_new_detailed_info = unchecked((int)0x809db6df);
    public const int destroy_auth_key_ok = unchecked((int)0xf660e1d4);
    public const int destroy_auth_key_none = unchecked((int)0x0a9f2259);
    public const int destroy_auth_key_fail = unchecked((int)0xea109b13);
    public const int req_pq_multi = unchecked((int)0xbe7e8ef1);
    public const int req_DH_params = unchecked((int)0xd712e4be);
    public const int set_client_DH_params = unchecked((int)0xf5045f1f);
    public const int rpc_drop_answer = unchecked((int)0x58e4a740);
    public const int get_future_salts = unchecked((int)0xb921bd04);
    public const int ping = unchecked((int)0x7abe77ec);
    public const int ping_delay_disconnect = unchecked((int)0xf3427b8c);
    public const int destroy_session = unchecked((int)0xe7512126);
    public const int http_wait = unchecked((int)0x9299359f);
    public const int destroy_auth_key = unchecked((int)0xd1435160);
    public const int boolFalse = unchecked((int)0xbc799737);
    public const int boolTrue = unchecked((int)0x997275b5);
    public const int error = unchecked((int)0xc4b9f9bb);
}
