//  <auto-generated>
//  This file was auto-generated by the Ferrite TL Generator.
//  Please do not modify as all changes will be lost.
//  <auto-generated/>

#nullable enable

using System.Runtime.InteropServices;
using Ferrite.TL.slim.mtproto;

namespace Ferrite.TL.slim;

public static class ObjectReader
{
    private static readonly Dictionary<int, ObjectReaderDelegate> _objectReaders = new();
    private static readonly Dictionary<int, ObjectSizeReaderDelegate> _sizeReaders = new();
    static ObjectReader()
    {
        _objectReaders.Add(unchecked((int)0x05162463), resPQ.Read);
        _sizeReaders.Add(unchecked((int)0x05162463), resPQ.ReadSize);
        _objectReaders.Add(unchecked((int)0x83c95aec), p_q_inner_data.Read);
        _sizeReaders.Add(unchecked((int)0x83c95aec), p_q_inner_data.ReadSize);
        _objectReaders.Add(unchecked((int)0x3c6a84d4), p_q_inner_data_temp.Read);
        _sizeReaders.Add(unchecked((int)0x3c6a84d4), p_q_inner_data_temp.ReadSize);
        _objectReaders.Add(unchecked((int)0xa9f55f95), p_q_inner_data_dc.Read);
        _sizeReaders.Add(unchecked((int)0xa9f55f95), p_q_inner_data_dc.ReadSize);
        _objectReaders.Add(unchecked((int)0x56fddf88), p_q_inner_data_temp_dc.Read);
        _sizeReaders.Add(unchecked((int)0x56fddf88), p_q_inner_data_temp_dc.ReadSize);
        _objectReaders.Add(unchecked((int)0xd0e8075c), server_DH_params_ok.Read);
        _sizeReaders.Add(unchecked((int)0xd0e8075c), server_DH_params_ok.ReadSize);
        _objectReaders.Add(unchecked((int)0xb5890dba), server_DH_inner_data.Read);
        _sizeReaders.Add(unchecked((int)0xb5890dba), server_DH_inner_data.ReadSize);
        _objectReaders.Add(unchecked((int)0x6643b654), client_DH_inner_data.Read);
        _sizeReaders.Add(unchecked((int)0x6643b654), client_DH_inner_data.ReadSize);
        _objectReaders.Add(unchecked((int)0x3bcbf734), dh_gen_ok.Read);
        _sizeReaders.Add(unchecked((int)0x3bcbf734), dh_gen_ok.ReadSize);
        _objectReaders.Add(unchecked((int)0x46dc1fb9), dh_gen_retry.Read);
        _sizeReaders.Add(unchecked((int)0x46dc1fb9), dh_gen_retry.ReadSize);
        _objectReaders.Add(unchecked((int)0xa69dae02), dh_gen_fail.Read);
        _sizeReaders.Add(unchecked((int)0xa69dae02), dh_gen_fail.ReadSize);
        _objectReaders.Add(unchecked((int)0x75a3f765), bind_auth_key_inner.Read);
        _sizeReaders.Add(unchecked((int)0x75a3f765), bind_auth_key_inner.ReadSize);
        _objectReaders.Add(unchecked((int)0xf35c6d01), rpc_result.Read);
        _sizeReaders.Add(unchecked((int)0xf35c6d01), rpc_result.ReadSize);
        _objectReaders.Add(unchecked((int)0x2144ca19), rpc_error.Read);
        _sizeReaders.Add(unchecked((int)0x2144ca19), rpc_error.ReadSize);
        _objectReaders.Add(unchecked((int)0x5e2ad36e), rpc_answer_unknown.Read);
        _sizeReaders.Add(unchecked((int)0x5e2ad36e), rpc_answer_unknown.ReadSize);
        _objectReaders.Add(unchecked((int)0xcd78e586), rpc_answer_dropped_running.Read);
        _sizeReaders.Add(unchecked((int)0xcd78e586), rpc_answer_dropped_running.ReadSize);
        _objectReaders.Add(unchecked((int)0xa43ad8b7), rpc_answer_dropped.Read);
        _sizeReaders.Add(unchecked((int)0xa43ad8b7), rpc_answer_dropped.ReadSize);
        _objectReaders.Add(unchecked((int)0x0949d9dc), future_salt.Read);
        _sizeReaders.Add(unchecked((int)0x0949d9dc), future_salt.ReadSize);
        _objectReaders.Add(unchecked((int)0xae500895), future_salts.Read);
        _sizeReaders.Add(unchecked((int)0xae500895), future_salts.ReadSize);
        _objectReaders.Add(unchecked((int)0x347773c5), pong.Read);
        _sizeReaders.Add(unchecked((int)0x347773c5), pong.ReadSize);
        _objectReaders.Add(unchecked((int)0xe22045fc), destroy_session_ok.Read);
        _sizeReaders.Add(unchecked((int)0xe22045fc), destroy_session_ok.ReadSize);
        _objectReaders.Add(unchecked((int)0x62d350c9), destroy_session_none.Read);
        _sizeReaders.Add(unchecked((int)0x62d350c9), destroy_session_none.ReadSize);
        _objectReaders.Add(unchecked((int)0x9ec20908), new_session_created.Read);
        _sizeReaders.Add(unchecked((int)0x9ec20908), new_session_created.ReadSize);
        _objectReaders.Add(unchecked((int)0x73f1f8dc), msg_container.Read);
        _sizeReaders.Add(unchecked((int)0x73f1f8dc), msg_container.ReadSize);
        _objectReaders.Add(unchecked((int)0xe06046b2), msg_copy.Read);
        _sizeReaders.Add(unchecked((int)0xe06046b2), msg_copy.ReadSize);
        _objectReaders.Add(unchecked((int)0x3072cfa1), gzip_packed.Read);
        _sizeReaders.Add(unchecked((int)0x3072cfa1), gzip_packed.ReadSize);
        _objectReaders.Add(unchecked((int)0x62d6b459), msgs_ack.Read);
        _sizeReaders.Add(unchecked((int)0x62d6b459), msgs_ack.ReadSize);
        _objectReaders.Add(unchecked((int)0xa7eff811), bad_msg_notification.Read);
        _sizeReaders.Add(unchecked((int)0xa7eff811), bad_msg_notification.ReadSize);
        _objectReaders.Add(unchecked((int)0xedab447b), bad_server_salt.Read);
        _sizeReaders.Add(unchecked((int)0xedab447b), bad_server_salt.ReadSize);
        _objectReaders.Add(unchecked((int)0x7d861a08), msg_resend_req.Read);
        _sizeReaders.Add(unchecked((int)0x7d861a08), msg_resend_req.ReadSize);
        _objectReaders.Add(unchecked((int)0xda69fb52), msgs_state_req.Read);
        _sizeReaders.Add(unchecked((int)0xda69fb52), msgs_state_req.ReadSize);
        _objectReaders.Add(unchecked((int)0x04deb57d), msgs_state_info.Read);
        _sizeReaders.Add(unchecked((int)0x04deb57d), msgs_state_info.ReadSize);
        _objectReaders.Add(unchecked((int)0x8cc0d131), msgs_all_info.Read);
        _sizeReaders.Add(unchecked((int)0x8cc0d131), msgs_all_info.ReadSize);
        _objectReaders.Add(unchecked((int)0x276d3ec6), msg_detailed_info.Read);
        _sizeReaders.Add(unchecked((int)0x276d3ec6), msg_detailed_info.ReadSize);
        _objectReaders.Add(unchecked((int)0x809db6df), msg_new_detailed_info.Read);
        _sizeReaders.Add(unchecked((int)0x809db6df), msg_new_detailed_info.ReadSize);
        _objectReaders.Add(unchecked((int)0xf660e1d4), destroy_auth_key_ok.Read);
        _sizeReaders.Add(unchecked((int)0xf660e1d4), destroy_auth_key_ok.ReadSize);
        _objectReaders.Add(unchecked((int)0x0a9f2259), destroy_auth_key_none.Read);
        _sizeReaders.Add(unchecked((int)0x0a9f2259), destroy_auth_key_none.ReadSize);
        _objectReaders.Add(unchecked((int)0xea109b13), destroy_auth_key_fail.Read);
        _sizeReaders.Add(unchecked((int)0xea109b13), destroy_auth_key_fail.ReadSize);
        _objectReaders.Add(unchecked((int)0xbe7e8ef1), req_pq_multi.Read);
        _sizeReaders.Add(unchecked((int)0xbe7e8ef1), req_pq_multi.ReadSize);
        _objectReaders.Add(unchecked((int)0xd712e4be), req_DH_params.Read);
        _sizeReaders.Add(unchecked((int)0xd712e4be), req_DH_params.ReadSize);
        _objectReaders.Add(unchecked((int)0xf5045f1f), set_client_DH_params.Read);
        _sizeReaders.Add(unchecked((int)0xf5045f1f), set_client_DH_params.ReadSize);
        _objectReaders.Add(unchecked((int)0x58e4a740), rpc_drop_answer.Read);
        _sizeReaders.Add(unchecked((int)0x58e4a740), rpc_drop_answer.ReadSize);
        _objectReaders.Add(unchecked((int)0xb921bd04), get_future_salts.Read);
        _sizeReaders.Add(unchecked((int)0xb921bd04), get_future_salts.ReadSize);
        _objectReaders.Add(unchecked((int)0x7abe77ec), ping.Read);
        _sizeReaders.Add(unchecked((int)0x7abe77ec), ping.ReadSize);
        _objectReaders.Add(unchecked((int)0xf3427b8c), ping_delay_disconnect.Read);
        _sizeReaders.Add(unchecked((int)0xf3427b8c), ping_delay_disconnect.ReadSize);
        _objectReaders.Add(unchecked((int)0xe7512126), destroy_session.Read);
        _sizeReaders.Add(unchecked((int)0xe7512126), destroy_session.ReadSize);
        _objectReaders.Add(unchecked((int)0x9299359f), http_wait.Read);
        _sizeReaders.Add(unchecked((int)0x9299359f), http_wait.ReadSize);
        _objectReaders.Add(unchecked((int)0xd1435160), destroy_auth_key.Read);
        _sizeReaders.Add(unchecked((int)0xd1435160), destroy_auth_key.ReadSize);
        _objectReaders.Add(unchecked((int)0xbc799737), boolFalse.Read);
        _sizeReaders.Add(unchecked((int)0xbc799737), boolFalse.ReadSize);
        _objectReaders.Add(unchecked((int)0x997275b5), boolTrue.Read);
        _sizeReaders.Add(unchecked((int)0x997275b5), boolTrue.ReadSize);
        _objectReaders.Add(unchecked((int)0xc4b9f9bb), error.Read);
        _sizeReaders.Add(unchecked((int)0xc4b9f9bb), error.ReadSize);
    }

    public static Span<byte> Read(Span<byte> buff)
    {
        if (buff.Length < 4)
        {
            return Span<byte>.Empty;
        }
        int constructor = MemoryMarshal.Read<int>(buff);
        if (_objectReaders.ContainsKey(constructor))
        {
            var reader = _objectReaders[constructor];
            return reader(buff, 0);
        }
        return Span<byte>.Empty;
    }
    public static Span<byte> Read(Span<byte> buff, int constructor)
    {
        if (buff.Length < 4)
        {
            return Span<byte>.Empty;
        }
        if (_objectReaders.ContainsKey(constructor))
        {
            var reader = _objectReaders[constructor];
            return reader(buff, 0);
        }
        return Span<byte>.Empty;
    }
    public static int ReadSize(Span<byte> buff)
    {
        if (buff.Length < 4)
        {
            return 0;
        }
        int constructor = MemoryMarshal.Read<int>(buff);
        if (_sizeReaders.ContainsKey(constructor))
        {
            var reader = _sizeReaders[constructor];
            return reader(buff, 0);
        }
        return 0;
    }
    public static int ReadSize(Span<byte> buff, int constructor)
    {
        if (buff.Length < 4)
        {
            return 0;
        }
        if (_sizeReaders.ContainsKey(constructor))
        {
            var reader = _sizeReaders[constructor];
            return reader.Invoke(buff, 0);
        }
        return 0;
    }
    public static ObjectReaderDelegate? GetObjectReader(int constructor)
    {
        if (_objectReaders.ContainsKey(constructor))
        {
            return _objectReaders[constructor];
        }

        return null;
    }
    public static ObjectSizeReaderDelegate? GetObjectSizeReader(int constructor)
    {
        if (_sizeReaders.ContainsKey(constructor))
        {
            return _sizeReaders[constructor];
        }

        return null;
    }
}
