//  <auto-generated>
//  This file was auto-generated by the Ferrite TL Generator.
//  Please do not modify as all changes will be lost.
//  <auto-generated/>

#nullable enable

using System.Buffers;
using System.Runtime.CompilerServices;
using Ferrite.Utils;

namespace Ferrite.TL.slim.mtproto;

public readonly unsafe struct client_DH_inner_data : ITLObjectReader, ITLSerializable
{
    private readonly byte* _buff;
    private readonly IMemoryOwner<byte>? _memoryOwner;
    private client_DH_inner_data(Span<byte> buffer, IMemoryOwner<byte> memoryOwner)
    {
        _buff = (byte*)Unsafe.AsPointer(ref buffer[0]);
        Length = buffer.Length;
        _memoryOwner = memoryOwner;
    }
    private client_DH_inner_data(byte* buffer, in int length, IMemoryOwner<byte> memoryOwner)
    {
        _buff = buffer;
        Length = length;
        _memoryOwner = memoryOwner;
    }
    
    public Client_DH_Inner_Data GetAsClient_DH_Inner_Data()
    {
        return new Client_DH_Inner_Data(_buff, Length, _memoryOwner);
    }
    public ref readonly int Constructor => ref *(int*)_buff;

    private void SetConstructor(int constructor)
    {
        var p = (int*)_buff;
        *p = constructor;
    }
    public int Length { get; }
    public ReadOnlySpan<byte> ToReadOnlySpan() => new (_buff, Length);
    public static ITLSerializable? Read(Span<byte> data, in int offset, out int bytesRead)
    {
        bytesRead = GetOffset(5, (byte*)Unsafe.AsPointer(ref data[offset..][0]), data.Length);
        var obj = new client_DH_inner_data(data.Slice(offset, bytesRead), null);
        return obj;
    }
    public static ITLSerializable? Read(byte* buffer, in int length, in int offset, out int bytesRead)
    {
        bytesRead = GetOffset(5, buffer + offset, length);
        var obj = new client_DH_inner_data(buffer + offset, bytesRead, null);
        return obj;
    }

    public static int GetRequiredBufferSize(int len_g_b)
    {
        return 4 + 16 + 16 + 8 + BufferUtils.CalculateTLBytesLength(len_g_b);
    }
    public static client_DH_inner_data Create(ReadOnlySpan<byte> nonce, ReadOnlySpan<byte> server_nonce, long retry_id, ReadOnlySpan<byte> g_b, MemoryPool<byte>? pool = null)
    {
        var length = GetRequiredBufferSize(g_b.Length);
        var memory = pool != null ? pool.Rent(length) : MemoryPool<byte>.Shared.Rent(length);
        memory.Memory.Span.Clear();
        var obj = new client_DH_inner_data(memory.Memory.Span[..length], memory);
        obj.SetConstructor(unchecked((int)0x6643b654));
        obj.Set_nonce(nonce);
        obj.Set_server_nonce(server_nonce);
        obj.Set_retry_id(retry_id);
        obj.Set_g_b(g_b);
        return obj;
    }
    public static int ReadSize(Span<byte> data, in int offset)
    {
        return GetOffset(5, (byte*)Unsafe.AsPointer(ref data[offset..][0]), data.Length);
    }

    public static int ReadSize(byte* buffer, in int length, in int offset)
    {
        return GetOffset(5, buffer + offset, length);
    }
    public ReadOnlySpan<byte> nonce => new (_buff + GetOffset(1, _buff, Length), 16);
    private void Set_nonce(ReadOnlySpan<byte> value)
    {
        if(value.Length != 16)
        {
            return;
        }
        fixed (byte* p = value)
        {
            int offset = GetOffset(1, _buff, Length);
            Buffer.MemoryCopy(p, _buff + offset,
                Length - offset, 16);
        }
    }
    public ReadOnlySpan<byte> server_nonce => new (_buff + GetOffset(2, _buff, Length), 16);
    private void Set_server_nonce(ReadOnlySpan<byte> value)
    {
        if(value.Length != 16)
        {
            return;
        }
        fixed (byte* p = value)
        {
            int offset = GetOffset(2, _buff, Length);
            Buffer.MemoryCopy(p, _buff + offset,
                Length - offset, 16);
        }
    }
    public ref readonly long retry_id => ref *(long*)(_buff + GetOffset(3, _buff, Length));
    private void Set_retry_id(in long value)
    {
        var p = (long*)(_buff + GetOffset(3, _buff, Length));
        *p = value;
    }
    public ReadOnlySpan<byte> g_b => BufferUtils.GetTLBytes(_buff, GetOffset(4, _buff, Length), Length);
    private void Set_g_b(ReadOnlySpan<byte> value)
    {
        if(value.Length == 0)
        {
            return;
        }
        var offset = GetOffset(4, _buff, Length);
        var lenBytes = BufferUtils.WriteLenBytes(_buff, value, offset, Length);
        fixed (byte* p = value)
        {
            Buffer.MemoryCopy(p, _buff + offset + lenBytes,
                Length - offset, value.Length);
        }
    }
    private static int GetOffset(int index, byte* buffer, int length)
    {
        int offset = 4;
        if(index >= 2) offset += 16;
        if(index >= 3) offset += 16;
        if(index >= 4) offset += 8;
        if(index >= 5) offset += BufferUtils.GetTLBytesLength(buffer, offset, length);
        return offset;
    }
    public void Dispose()
    {
        _memoryOwner?.Dispose();
    }
}
