//  <auto-generated>
//  This file was auto-generated by the Ferrite TL Generator.
//  Please do not modify as all changes will be lost.
//  <auto-generated/>

#nullable enable

using System.Buffers;
using System.Runtime.InteropServices;
using Ferrite.Utils;

namespace Ferrite.TL.slim.mtproto;

public readonly ref struct future_salts
{
    private readonly Span<byte> _buff;
    public future_salts(Span<byte> buff)
    {
        _buff = buff;
    }
    
    public readonly int Constructor => MemoryMarshal.Read<int>(_buff);

    private void SetConstructor(int constructor)
    {
        MemoryMarshal.Write(_buff.Slice(0, 4), ref constructor);
    }
    public int Length => _buff.Length;
    public ReadOnlySpan<byte> ToReadOnlySpan() => _buff;
    public static Span<byte> Read(Span<byte> data, int offset)
    {
        var bytesRead = GetOffset(4, data[offset..]);
        if (bytesRead > data.Length + offset)
        {
            return Span<byte>.Empty;
        }
        return data.Slice(offset, bytesRead);
    }

    public static int GetRequiredBufferSize(int len_salts)
    {
        return 4 + 8 + 4 + len_salts;
    }
    public static future_salts Create(long req_msg_id, int now, VectorBare salts, out IMemoryOwner<byte> memory, MemoryPool<byte>? pool = null)
    {
        var length = GetRequiredBufferSize(salts.Length);
        memory = pool != null ? pool.Rent(length) : MemoryPool<byte>.Shared.Rent(length);
        memory.Memory.Span.Clear();
        var obj = new future_salts(memory.Memory.Span[..length]);
        obj.SetConstructor(unchecked((int)0xae500895));
        obj.Set_req_msg_id(req_msg_id);
        obj.Set_now(now);
        obj.Set_salts(salts.ToReadOnlySpan());
        return obj;
    }
    public static int ReadSize(Span<byte> data, int offset)
    {
        return GetOffset(4, data[offset..]);
    }
    public readonly long req_msg_id => MemoryMarshal.Read<long>(_buff[GetOffset(1, _buff)..]);
    private void Set_req_msg_id(long value)
    {
        MemoryMarshal.Write(_buff[GetOffset(1, _buff)..], ref value);
    }
    public readonly int now => MemoryMarshal.Read<int>(_buff[GetOffset(2, _buff)..]);
    private void Set_now(int value)
    {
        MemoryMarshal.Write(_buff[GetOffset(2, _buff)..], ref value);
    }
    public VectorBare salts => new VectorBare(_buff.Slice(GetOffset(3, _buff)));
    private void Set_salts(ReadOnlySpan<byte> value)
    {
        value.CopyTo(_buff[GetOffset(3, _buff)..]);
    }
    private static int GetOffset(int index, Span<byte> buffer)
    {
        int offset = 4;
        if(index >= 2) offset += 8;
        if(index >= 3) offset += 4;
        if(index >= 4) offset += VectorBare.ReadSize(buffer, offset);
        return offset;
    }
}
