//  <auto-generated>
//  This file was auto-generated by the Ferrite TL Generator.
//  Please do not modify as all changes will be lost.
//  <auto-generated/>

#nullable enable

using System.Buffers;
using System.Runtime.InteropServices;
using Ferrite.Utils;
using DotNext.Buffers;

namespace Ferrite.TL.slim.mtproto;

public readonly ref struct future_salts
{
    private readonly Span<byte> _buff;
    private readonly IMemoryOwner<byte>? _memory;
    public future_salts(long req_msg_id, int now, VectorBare salts)
    {
        var length = GetRequiredBufferSize(salts.Length);
        _memory = UnmanagedMemoryPool<byte>.Shared.Rent(length);
        _memory.Memory.Span.Clear();
        _buff = _memory.Memory.Span[..length];
        SetConstructor(unchecked((int)0xae500895));
        Set_req_msg_id(req_msg_id);
        Set_now(now);
        Set_salts(salts.ToReadOnlySpan());
    }
    public future_salts(Span<byte> buff)
    {
        _buff = buff;
    }
    
    public readonly int Constructor => MemoryMarshal.Read<int>(_buff);

    private void SetConstructor(int constructor)
    {
        MemoryMarshal.Write(_buff.Slice(0, 4), ref constructor);
    }
    public int Length => _buff.Length;
    public ReadOnlySpan<byte> ToReadOnlySpan() => _buff;
    public TLBytes? TLBytes => _memory != null ? new TLBytes(_memory, 0, _buff.Length) : null;
    public static Span<byte> Read(Span<byte> data, int offset)
    {
        var bytesRead = GetOffset(4, data[offset..]);
        if (bytesRead > data.Length + offset)
        {
            return Span<byte>.Empty;
        }
        return data.Slice(offset, bytesRead);
    }

    public static int GetRequiredBufferSize(int len_salts)
    {
        return 4 + 8 + 4 + len_salts;
    }
    public static int ReadSize(Span<byte> data, int offset)
    {
        return GetOffset(4, data[offset..]);
    }
    public readonly long req_msg_id => MemoryMarshal.Read<long>(_buff[GetOffset(1, _buff)..]);
    private void Set_req_msg_id(long value)
    {
        MemoryMarshal.Write(_buff[GetOffset(1, _buff)..], ref value);
    }
    public readonly int now => MemoryMarshal.Read<int>(_buff[GetOffset(2, _buff)..]);
    private void Set_now(int value)
    {
        MemoryMarshal.Write(_buff[GetOffset(2, _buff)..], ref value);
    }
    public VectorBare salts => new VectorBare(_buff.Slice(GetOffset(3, _buff)));
    private void Set_salts(ReadOnlySpan<byte> value)
    {
        value.CopyTo(_buff[GetOffset(3, _buff)..]);
    }
    private static int GetOffset(int index, Span<byte> buffer)
    {
        int offset = 4;
        if(index >= 2) offset += 8;
        if(index >= 3) offset += 4;
        if(index >= 4) offset += VectorBare.ReadSize(buffer, offset);
        return offset;
    }
    public ref struct TLObjectBuilder
    {
        private long _req_msg_id;
        public TLObjectBuilder with_req_msg_id(long value)
        {
            _req_msg_id = value;
            return this;
        }
        private int _now;
        public TLObjectBuilder with_now(int value)
        {
            _now = value;
            return this;
        }
        private VectorBare _salts;
        public TLObjectBuilder with_salts(VectorBare value)
        {
            _salts = value;
            return this;
        }
        public future_salts Build()
        {
            return new future_salts(_req_msg_id, _now, _salts);
        }
    }

    public static TLObjectBuilder Builder()
    {
        return new TLObjectBuilder();
    }
    public void Dispose()
    {
        _memory?.Dispose();
    }
}
