//  <auto-generated>
//  This file was auto-generated by the Ferrite TL Generator.
//  Please do not modify as all changes will be lost.
//  <auto-generated/>

#nullable enable

using System.Buffers;
using System.Runtime.InteropServices;
using Ferrite.Utils;
using DotNext.Buffers;

namespace Ferrite.TL.slim.mtproto;

public readonly ref struct msg_container
{
    private readonly Span<byte> _buff;
    private readonly IMemoryOwner<byte>? _memory;
    public msg_container(VectorBare messages)
    {
        var length = GetRequiredBufferSize(messages.Length);
        _memory = UnmanagedMemoryPool<byte>.Shared.Rent(length);
        _memory.Memory.Span.Clear();
        _buff = _memory.Memory.Span[..length];
        SetConstructor(unchecked((int)0x73f1f8dc));
        Set_messages(messages.ToReadOnlySpan());
    }
    public msg_container(Span<byte> buff)
    {
        _buff = buff;
    }
    
    public readonly int Constructor => MemoryMarshal.Read<int>(_buff);

    private void SetConstructor(int constructor)
    {
        MemoryMarshal.Write(_buff.Slice(0, 4), ref constructor);
    }
    public int Length => _buff.Length;
    public ReadOnlySpan<byte> ToReadOnlySpan() => _buff;
    public TLBytes? TLBytes => _memory != null ? new TLBytes(_memory, 0, _buff.Length) : null;
    public static Span<byte> Read(Span<byte> data, int offset)
    {
        var bytesRead = GetOffset(2, data[offset..]);
        if (bytesRead > data.Length + offset)
        {
            return Span<byte>.Empty;
        }
        return data.Slice(offset, bytesRead);
    }

    public static int GetRequiredBufferSize(int len_messages)
    {
        return 4 + len_messages;
    }
    public static int ReadSize(Span<byte> data, int offset)
    {
        return GetOffset(2, data[offset..]);
    }
    public VectorBare messages => new VectorBare(_buff.Slice(GetOffset(1, _buff)));
    private void Set_messages(ReadOnlySpan<byte> value)
    {
        value.CopyTo(_buff[GetOffset(1, _buff)..]);
    }
    private static int GetOffset(int index, Span<byte> buffer)
    {
        int offset = 4;
        if(index >= 2) offset += VectorBare.ReadSize(buffer, offset);
        return offset;
    }
    public ref struct TLObjectBuilder
    {
        private VectorBare _messages;
        public TLObjectBuilder with_messages(VectorBare value)
        {
            _messages = value;
            return this;
        }
        public msg_container Build()
        {
            return new msg_container(_messages);
        }
    }

    public static TLObjectBuilder Builder()
    {
        return new TLObjectBuilder();
    }
    public void Dispose()
    {
        _memory?.Dispose();
    }
}
