//  <auto-generated>
//  This file was auto-generated by the Ferrite TL Generator.
//  Please do not modify as all changes will be lost.
//  <auto-generated/>

#nullable enable

using System.Buffers;
using System.Runtime.InteropServices;
using Ferrite.Utils;
using DotNext.Buffers;

namespace Ferrite.TL.slim.mtproto;

public readonly ref struct p_q_inner_data_dc
{
    private readonly Span<byte> _buff;
    private readonly IMemoryOwner<byte>? _memory;
    public p_q_inner_data_dc(ReadOnlySpan<byte> pq, ReadOnlySpan<byte> p, ReadOnlySpan<byte> q, ReadOnlySpan<byte> nonce, ReadOnlySpan<byte> server_nonce, ReadOnlySpan<byte> new_nonce, int dc)
    {
        var length = GetRequiredBufferSize(pq.Length, p.Length, q.Length);
        _memory = UnmanagedMemoryPool<byte>.Shared.Rent(length);
        _memory.Memory.Span.Clear();
        _buff = _memory.Memory.Span[..length];
        SetConstructor(unchecked((int)0xa9f55f95));
        Set_pq(pq);
        Set_p(p);
        Set_q(q);
        Set_nonce(nonce);
        Set_server_nonce(server_nonce);
        Set_new_nonce(new_nonce);
        Set_dc(dc);
    }public p_q_inner_data_dc(Span<byte> buff)
    {
        _buff = buff;
    }
    
    public readonly int Constructor => MemoryMarshal.Read<int>(_buff);

    private void SetConstructor(int constructor)
    {
        MemoryMarshal.Write(_buff.Slice(0, 4), ref constructor);
    }
    public int Length => _buff.Length;
    public ReadOnlySpan<byte> ToReadOnlySpan() => _buff;
    public TLBytes? TLBytes => _memory != null ? new TLBytes(_memory, 0, _buff.Length) : null;
    public static Span<byte> Read(Span<byte> data, int offset)
    {
        var bytesRead = GetOffset(8, data[offset..]);
        if (bytesRead > data.Length + offset)
        {
            return Span<byte>.Empty;
        }
        return data.Slice(offset, bytesRead);
    }

    public static int GetRequiredBufferSize(int len_pq, int len_p, int len_q)
    {
        return 4 + BufferUtils.CalculateTLBytesLength(len_pq) + BufferUtils.CalculateTLBytesLength(len_p) + BufferUtils.CalculateTLBytesLength(len_q) + 16 + 16 + 32 + 4;
    }
    public static int ReadSize(Span<byte> data, int offset)
    {
        return GetOffset(8, data[offset..]);
    }
    public ReadOnlySpan<byte> pq => BufferUtils.GetTLBytes(_buff, GetOffset(1, _buff));
    private void Set_pq(ReadOnlySpan<byte> value)
    {
        if(value.Length == 0)
        {
            return;
        }
        var offset = GetOffset(1, _buff);
        var lenBytes = BufferUtils.WriteLenBytes(_buff, value, offset);
        if(_buff.Length < offset + lenBytes + value.Length) return;
        value.CopyTo(_buff[(offset + lenBytes)..]);
    }
    public ReadOnlySpan<byte> p => BufferUtils.GetTLBytes(_buff, GetOffset(2, _buff));
    private void Set_p(ReadOnlySpan<byte> value)
    {
        if(value.Length == 0)
        {
            return;
        }
        var offset = GetOffset(2, _buff);
        var lenBytes = BufferUtils.WriteLenBytes(_buff, value, offset);
        if(_buff.Length < offset + lenBytes + value.Length) return;
        value.CopyTo(_buff[(offset + lenBytes)..]);
    }
    public ReadOnlySpan<byte> q => BufferUtils.GetTLBytes(_buff, GetOffset(3, _buff));
    private void Set_q(ReadOnlySpan<byte> value)
    {
        if(value.Length == 0)
        {
            return;
        }
        var offset = GetOffset(3, _buff);
        var lenBytes = BufferUtils.WriteLenBytes(_buff, value, offset);
        if(_buff.Length < offset + lenBytes + value.Length) return;
        value.CopyTo(_buff[(offset + lenBytes)..]);
    }
    public ReadOnlySpan<byte> nonce => _buff.Slice(GetOffset(4, _buff), 16);
    private void Set_nonce(ReadOnlySpan<byte> value)
    {
        if(value.Length != 16)
        {
            return;
        }
        value.CopyTo(_buff.Slice(GetOffset(4, _buff), 16));
    }
    public ReadOnlySpan<byte> server_nonce => _buff.Slice(GetOffset(5, _buff), 16);
    private void Set_server_nonce(ReadOnlySpan<byte> value)
    {
        if(value.Length != 16)
        {
            return;
        }
        value.CopyTo(_buff.Slice(GetOffset(5, _buff), 16));
    }
    public ReadOnlySpan<byte> new_nonce => _buff.Slice(GetOffset(6, _buff), 32);
    private void Set_new_nonce(ReadOnlySpan<byte> value)
    {
        if(value.Length != 32)
        {
            return;
        }
        value.CopyTo(_buff.Slice(GetOffset(6, _buff), 32));
    }
    public readonly int dc => MemoryMarshal.Read<int>(_buff[GetOffset(7, _buff)..]);
    private void Set_dc(int value)
    {
        MemoryMarshal.Write(_buff[GetOffset(7, _buff)..], ref value);
    }
    private static int GetOffset(int index, Span<byte> buffer)
    {
        int offset = 4;
        if(index >= 2) offset += BufferUtils.GetTLBytesLength(buffer, offset);
        if(index >= 3) offset += BufferUtils.GetTLBytesLength(buffer, offset);
        if(index >= 4) offset += BufferUtils.GetTLBytesLength(buffer, offset);
        if(index >= 5) offset += 16;
        if(index >= 6) offset += 16;
        if(index >= 7) offset += 32;
        if(index >= 8) offset += 4;
        return offset;
    }
    public void Dispose()
    {
        _memory?.Dispose();
    }
}
