//  <auto-generated>
//  This file was auto-generated by the Ferrite TL Generator.
//  Please do not modify as all changes will be lost.
//  <auto-generated/>

#nullable enable

using System.Buffers;
using System.Runtime.InteropServices;
using Ferrite.Utils;
using DotNext.Buffers;

namespace Ferrite.TL.slim.mtproto;

public readonly ref struct resPQ
{
    private readonly Span<byte> _buff;
    private readonly IMemoryOwner<byte>? _memory;
    public resPQ(ReadOnlySpan<byte> nonce, ReadOnlySpan<byte> server_nonce, ReadOnlySpan<byte> pq, VectorOfLong server_public_key_fingerprints)
    {
        var length = GetRequiredBufferSize(pq.Length, server_public_key_fingerprints.Length);
        _memory = UnmanagedMemoryPool<byte>.Shared.Rent(length);
        _memory.Memory.Span.Clear();
        _buff = _memory.Memory.Span[..length];
        SetConstructor(unchecked((int)0x05162463));
        Set_nonce(nonce);
        Set_server_nonce(server_nonce);
        Set_pq(pq);
        Set_server_public_key_fingerprints(server_public_key_fingerprints.ToReadOnlySpan());
    }
    public resPQ(Span<byte> buff)
    {
        _buff = buff;
    }
    
    public readonly int Constructor => MemoryMarshal.Read<int>(_buff);

    private void SetConstructor(int constructor)
    {
        MemoryMarshal.Write(_buff.Slice(0, 4), ref constructor);
    }
    public int Length => _buff.Length;
    public ReadOnlySpan<byte> ToReadOnlySpan() => _buff;
    public TLBytes? TLBytes => _memory != null ? new TLBytes(_memory, 0, _buff.Length) : null;
    public static Span<byte> Read(Span<byte> data, int offset)
    {
        var bytesRead = GetOffset(5, data[offset..]);
        if (bytesRead > data.Length + offset)
        {
            return Span<byte>.Empty;
        }
        return data.Slice(offset, bytesRead);
    }

    public static int GetRequiredBufferSize(int len_pq, int len_server_public_key_fingerprints)
    {
        return 4 + 16 + 16 + BufferUtils.CalculateTLBytesLength(len_pq) + len_server_public_key_fingerprints;
    }
    public static int ReadSize(Span<byte> data, int offset)
    {
        return GetOffset(5, data[offset..]);
    }
    public ReadOnlySpan<byte> nonce => _buff.Slice(GetOffset(1, _buff), 16);
    private void Set_nonce(ReadOnlySpan<byte> value)
    {
        if(value.Length != 16)
        {
            return;
        }
        value.CopyTo(_buff.Slice(GetOffset(1, _buff), 16));
    }
    public ReadOnlySpan<byte> server_nonce => _buff.Slice(GetOffset(2, _buff), 16);
    private void Set_server_nonce(ReadOnlySpan<byte> value)
    {
        if(value.Length != 16)
        {
            return;
        }
        value.CopyTo(_buff.Slice(GetOffset(2, _buff), 16));
    }
    public ReadOnlySpan<byte> pq => BufferUtils.GetTLBytes(_buff, GetOffset(3, _buff));
    private void Set_pq(ReadOnlySpan<byte> value)
    {
        if(value.Length == 0)
        {
            return;
        }
        var offset = GetOffset(3, _buff);
        var lenBytes = BufferUtils.WriteLenBytes(_buff, value, offset);
        if(_buff.Length < offset + lenBytes + value.Length) return;
        value.CopyTo(_buff[(offset + lenBytes)..]);
    }
    public VectorOfLong server_public_key_fingerprints => new VectorOfLong(_buff.Slice(GetOffset(4, _buff)));
    private void Set_server_public_key_fingerprints(ReadOnlySpan<byte> value)
    {
        value.CopyTo(_buff[GetOffset(4, _buff)..]);
    }
    private static int GetOffset(int index, Span<byte> buffer)
    {
        int offset = 4;
        if(index >= 2) offset += 16;
        if(index >= 3) offset += 16;
        if(index >= 4) offset += BufferUtils.GetTLBytesLength(buffer, offset);
        if(index >= 5) offset += VectorOfLong.ReadSize(buffer, offset);
        return offset;
    }
    public ref struct TLObjectBuilder
    {
        private ReadOnlySpan<byte> _nonce;
        public TLObjectBuilder with_nonce(ReadOnlySpan<byte> value)
        {
            _nonce = value;
            return this;
        }
        private ReadOnlySpan<byte> _server_nonce;
        public TLObjectBuilder with_server_nonce(ReadOnlySpan<byte> value)
        {
            _server_nonce = value;
            return this;
        }
        private ReadOnlySpan<byte> _pq;
        public TLObjectBuilder with_pq(ReadOnlySpan<byte> value)
        {
            _pq = value;
            return this;
        }
        private VectorOfLong _server_public_key_fingerprints;
        public TLObjectBuilder with_server_public_key_fingerprints(VectorOfLong value)
        {
            _server_public_key_fingerprints = value;
            return this;
        }
        public resPQ Build()
        {
            return new resPQ(_nonce, _server_nonce, _pq, _server_public_key_fingerprints);
        }
    }

    public static TLObjectBuilder Builder()
    {
        return new TLObjectBuilder();
    }
    public void Dispose()
    {
        _memory?.Dispose();
    }
}
