//  <auto-generated>
//  This file was auto-generated by the Ferrite TL Generator.
//  Please do not modify as all changes will be lost.
//  <auto-generated/>

#nullable enable

using System.Buffers;
using System.Runtime.InteropServices;
using Ferrite.Utils;
using DotNext.Buffers;

namespace Ferrite.TL.slim.mtproto;

public readonly ref struct rpc_error
{
    private readonly Span<byte> _buff;
    private readonly IMemoryOwner<byte>? _memory;
    public rpc_error(int error_code, ReadOnlySpan<byte> error_message)
    {
        var length = GetRequiredBufferSize(error_message.Length);
        _memory = UnmanagedMemoryPool<byte>.Shared.Rent(length);
        _memory.Memory.Span.Clear();
        _buff = _memory.Memory.Span[..length];
        SetConstructor(unchecked((int)0x2144ca19));
        Set_error_code(error_code);
        Set_error_message(error_message);
    }
    public rpc_error(Span<byte> buff)
    {
        _buff = buff;
    }
    
    public readonly int Constructor => MemoryMarshal.Read<int>(_buff);

    private void SetConstructor(int constructor)
    {
        MemoryMarshal.Write(_buff.Slice(0, 4), ref constructor);
    }
    public int Length => _buff.Length;
    public ReadOnlySpan<byte> ToReadOnlySpan() => _buff;
    public TLBytes? TLBytes => _memory != null ? new TLBytes(_memory, 0, _buff.Length) : null;
    public static Span<byte> Read(Span<byte> data, int offset)
    {
        var bytesRead = GetOffset(3, data[offset..]);
        if (bytesRead > data.Length + offset)
        {
            return Span<byte>.Empty;
        }
        return data.Slice(offset, bytesRead);
    }

    public static int GetRequiredBufferSize(int len_error_message)
    {
        return 4 + 4 + BufferUtils.CalculateTLBytesLength(len_error_message);
    }
    public static int ReadSize(Span<byte> data, int offset)
    {
        return GetOffset(3, data[offset..]);
    }
    public readonly int error_code => MemoryMarshal.Read<int>(_buff[GetOffset(1, _buff)..]);
    private void Set_error_code(int value)
    {
        MemoryMarshal.Write(_buff[GetOffset(1, _buff)..], ref value);
    }
    public ReadOnlySpan<byte> error_message => BufferUtils.GetTLBytes(_buff, GetOffset(2, _buff));
    private void Set_error_message(ReadOnlySpan<byte> value)
    {
        if(value.Length == 0)
        {
            return;
        }
        var offset = GetOffset(2, _buff);
        var lenBytes = BufferUtils.WriteLenBytes(_buff, value, offset);
        if(_buff.Length < offset + lenBytes + value.Length) return;
        value.CopyTo(_buff[(offset + lenBytes)..]);
    }
    private static int GetOffset(int index, Span<byte> buffer)
    {
        int offset = 4;
        if(index >= 2) offset += 4;
        if(index >= 3) offset += BufferUtils.GetTLBytesLength(buffer, offset);
        return offset;
    }
    public ref struct TLObjectBuilder
    {
        private int _error_code;
        public TLObjectBuilder with_error_code(int value)
        {
            _error_code = value;
            return this;
        }
        private ReadOnlySpan<byte> _error_message;
        public TLObjectBuilder with_error_message(ReadOnlySpan<byte> value)
        {
            _error_message = value;
            return this;
        }
        public rpc_error Build()
        {
            return new rpc_error(_error_code, _error_message);
        }
    }

    public static TLObjectBuilder Builder()
    {
        return new TLObjectBuilder();
    }
    public void Dispose()
    {
        _memory?.Dispose();
    }
}
