//  <auto-generated>
//  This file was auto-generated by the Ferrite TL Generator.
//  Please do not modify as all changes will be lost.
//  <auto-generated/>

#nullable enable

using System.Buffers;
using System.Runtime.InteropServices;
using Ferrite.Utils;
using DotNext.Buffers;

namespace Ferrite.TL.slim.mtproto;

public readonly ref struct server_DH_inner_data
{
    private readonly Span<byte> _buff;
    private readonly IMemoryOwner<byte>? _memory;
    public server_DH_inner_data(ReadOnlySpan<byte> nonce, ReadOnlySpan<byte> server_nonce, int g, ReadOnlySpan<byte> dh_prime, ReadOnlySpan<byte> g_a, int server_time)
    {
        var length = GetRequiredBufferSize(dh_prime.Length, g_a.Length);
        _memory = UnmanagedMemoryPool<byte>.Shared.Rent(length);
        _memory.Memory.Span.Clear();
        _buff = _memory.Memory.Span[..length];
        SetConstructor(unchecked((int)0xb5890dba));
        Set_nonce(nonce);
        Set_server_nonce(server_nonce);
        Set_g(g);
        Set_dh_prime(dh_prime);
        Set_g_a(g_a);
        Set_server_time(server_time);
    }public server_DH_inner_data(Span<byte> buff)
    {
        _buff = buff;
    }
    
    public readonly int Constructor => MemoryMarshal.Read<int>(_buff);

    private void SetConstructor(int constructor)
    {
        MemoryMarshal.Write(_buff.Slice(0, 4), ref constructor);
    }
    public int Length => _buff.Length;
    public ReadOnlySpan<byte> ToReadOnlySpan() => _buff;
    public TLBytes? TLBytes => _memory != null ? new TLBytes(_memory, 0, _buff.Length) : null;
    public static Span<byte> Read(Span<byte> data, int offset)
    {
        var bytesRead = GetOffset(7, data[offset..]);
        if (bytesRead > data.Length + offset)
        {
            return Span<byte>.Empty;
        }
        return data.Slice(offset, bytesRead);
    }

    public static int GetRequiredBufferSize(int len_dh_prime, int len_g_a)
    {
        return 4 + 16 + 16 + 4 + BufferUtils.CalculateTLBytesLength(len_dh_prime) + BufferUtils.CalculateTLBytesLength(len_g_a) + 4;
    }
    public static int ReadSize(Span<byte> data, int offset)
    {
        return GetOffset(7, data[offset..]);
    }
    public ReadOnlySpan<byte> nonce => _buff.Slice(GetOffset(1, _buff), 16);
    private void Set_nonce(ReadOnlySpan<byte> value)
    {
        if(value.Length != 16)
        {
            return;
        }
        value.CopyTo(_buff.Slice(GetOffset(1, _buff), 16));
    }
    public ReadOnlySpan<byte> server_nonce => _buff.Slice(GetOffset(2, _buff), 16);
    private void Set_server_nonce(ReadOnlySpan<byte> value)
    {
        if(value.Length != 16)
        {
            return;
        }
        value.CopyTo(_buff.Slice(GetOffset(2, _buff), 16));
    }
    public readonly int g => MemoryMarshal.Read<int>(_buff[GetOffset(3, _buff)..]);
    private void Set_g(int value)
    {
        MemoryMarshal.Write(_buff[GetOffset(3, _buff)..], ref value);
    }
    public ReadOnlySpan<byte> dh_prime => BufferUtils.GetTLBytes(_buff, GetOffset(4, _buff));
    private void Set_dh_prime(ReadOnlySpan<byte> value)
    {
        if(value.Length == 0)
        {
            return;
        }
        var offset = GetOffset(4, _buff);
        var lenBytes = BufferUtils.WriteLenBytes(_buff, value, offset);
        if(_buff.Length < offset + lenBytes + value.Length) return;
        value.CopyTo(_buff[(offset + lenBytes)..]);
    }
    public ReadOnlySpan<byte> g_a => BufferUtils.GetTLBytes(_buff, GetOffset(5, _buff));
    private void Set_g_a(ReadOnlySpan<byte> value)
    {
        if(value.Length == 0)
        {
            return;
        }
        var offset = GetOffset(5, _buff);
        var lenBytes = BufferUtils.WriteLenBytes(_buff, value, offset);
        if(_buff.Length < offset + lenBytes + value.Length) return;
        value.CopyTo(_buff[(offset + lenBytes)..]);
    }
    public readonly int server_time => MemoryMarshal.Read<int>(_buff[GetOffset(6, _buff)..]);
    private void Set_server_time(int value)
    {
        MemoryMarshal.Write(_buff[GetOffset(6, _buff)..], ref value);
    }
    private static int GetOffset(int index, Span<byte> buffer)
    {
        int offset = 4;
        if(index >= 2) offset += 16;
        if(index >= 3) offset += 16;
        if(index >= 4) offset += 4;
        if(index >= 5) offset += BufferUtils.GetTLBytesLength(buffer, offset);
        if(index >= 6) offset += BufferUtils.GetTLBytesLength(buffer, offset);
        if(index >= 7) offset += 4;
        return offset;
    }
    public void Dispose()
    {
        _memory?.Dispose();
    }
}
